spring:
  application:
    name: starwars-api

  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:starwarsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        disable-ssl-validation: true
        enabled: false

services:
  swapi:
    name: startwars-api
    url: https://swapi.dev/api
    endpoint-films: /films
    endpoint-people: /people
    endpoint-planets: /planets
    endpoint-starships: /starships
    endpoint-vehicles: /vehicles
    endpoint-species: /species

logging:
  level:
    br.com.starwars.api.external.gateway: DEBUG